language: 
  - cpp 
install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake octave liboctave-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
