dist: trusty
language:  cpp
compiler : gcc
before_install:
  - sudo apt-add-repository -y ppa:picaso/octave
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq octave
  - sudo apt-get install -qq liboctave-dev
  - sudo apt-get install -qq libeigen3-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
