os:
  - osx
language: 
  - objective-c
compiler:
  - clang
before_install:
  - brew update
  - brew tap homebrew/science
# Change this to your needs
  - brew install cmake octave
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
