########################################################################
## * not all components will be configured
## * build only on a 64-bit environment
## * only builds for release configuration
##
## FAIL: The build takes too long, most components are disabled.
## TODO: but build takes too long... 40 min limit
## * run the self tests after install
########################################################################

version: '{build}'

platform: Win32

configuration:
  - Debug

environment:
  global:
    GENERATOR: Visual Studio 12 2013

# Operating system (build VM template)
os: Windows Server 2012 R2

# branches to build
branches:
  # whitelist
  only:
    - master

before_build:
  - choco install octave
  - set PATH=%PATH%;C:\Software\Octave-3.6.4\bin

# configure and build
build_script:
  - mkdir build && cd build
  - cmake ../ -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cmake --build . --config %CONFIGURATION%

